### PR TITLE
re-base on Python slim image instead of mamba

### PR DESCRIPTION
**Pull request by joefutrelle**
This reduces the Docker image size by about 50%.

### CODE REVIEW

**Comment by joefutrelle** [comment]
Are you making requests during this period, or does this happen when no requests have come in for a while?

**Comment by joannekoch** [comment]
It seems to happen for both, when I make a request and then if I shut it down and restart it, and do nothing, it happens.

**Comment by joefutrelle** [comment]
I'm not seeing this behavior in either scenario.

**Comment by joannekoch** [comment]
The above error happens when I run http://localhost:8000/api/ctd/en608/bottles.csv. The error is intermitten and it seems to happen when the end point takes longer to complete than other times when it is run.

**Pull request merged**
