### PR TITLE
Merge bottle summary only if btl data exists for the cruise

### PR DESCRIPTION
**Pull request by joannekoch**
For the ep /api/chl/all.csv, modify `merge_bottle_summary` to merge bottle summary data with chlorophyll data only if bottle summary data exists for the cruise.

Fixes a bug in the code where ar44 and ar66a were included in all_chl.csv when they shouldn't have been.

### CODE REVIEW

**Comment by katemorkeski** [comment]
For any cruises without btl data, chlorophyll data should be retained, not dropped

**Comment by joannekoch** [comment]
@katemorkeski, chlorophyll for a single cruise results in a not found error if there's no bottle data. Try running /api/chl/ar44.csv. What you are asking for is not how the api is currently implemented.

**Comment by joefutrelle** [comment]
I think the idea is to change the API so it serves the chl data in those cases (like ar66a) where there are entries in the chl spreadsheet but there is no bottle data to merge.

**Comment by joannekoch** [comment]
If that's the case, then a new Issue should be opened. It sounds like an enhancement to me.

**Comment by joannekoch** [comment]
In the weekly team meeting today, the following was decided:

1. The CHL ep for a single cruise (i.e. https://nes-lter-data.whoi.edu/api/chl/en644.csv) will return a 'not found' error when there is no bottle data.
2. The CHL ep for all cruises (i.e. https://nes-lter-data.whoi.edu/api/chl/all.csv) return only chlorophyll data for cruises that do not have bottle data. All cruises with chlorophyll and bottle data will be included in the output.

**Review by joannekoch — COMMENTED** [review]
fix merge bug when cruise is NaN

**Comment by joefutrelle** [comment]
Tested. LGTM

**Pull request merged**
